#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
 
echo '🏗️👷 Styling and checking your project before committing👷‍♂️🏗️'
echo 'please be patient, this may take a while...'

# Check Git user email
GIT_USER_EMAIL=$(git config user.email)

if [[ "$GIT_USER_EMAIL" == *"@nexondv.com"* ]]; then
  echo '🔨❌ Oops! Your Git user email contains "@nexondv.com" 🔨❌. 
              Please change to your personal email '
  false
fi
 
# Check ESLint Standards
yarn lint ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
          Run yarn lint, add changes and try commit again.';
    false;
)

# Try building to check if there is any error
yarn build ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check terminal 🔨❌
          Add changes and try commit again.';
    false;
)
 
echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'
 
npx lint-staged